script:
  - bundle exec rake test

language: ruby
rvm:
  - 2.5.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route build to the container-based infrastructure for a faster build
