exclude: [Gemfile, Gemfile.lock, params.json, README.md, Rakefile]
relative_permalinks: false
permalink: /:title/
url: "https://johanpeeters.com"
plugins:
  - jekyll-sitemap
sass:
  style: compressed
assets:
  css_compressor: sass
markdown: kramdown
